- name: Install packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=86400
  become: True
  with_items: "{{packages}}"

- name: Ensure resolvconf is gone, because it's evil
  apt: pkg=resolvconf state=absent
  become: True
